### ISSUE TITLE
check_mk-Paket nicht auffindbar

### ISSUE THREAD

**Issue by bwildenhain** [eulenfunk/docs#16]
wget "https://monitoring.eulenfunk.de/heimathoster/check_mk/agents/check-mk-agent_1.2.8p1-1_all.deb" (Serverkochbuch) -> 404

**Comment by jjx-** [comment]
https://monitoring.eulenfunk.de/eulenfunk/check_mk/agents/check-mk-agent_1.2.8p11-1_all.deb
wäre aktuell korrekt
